In [1]:
import numpy as np

In [2]:
class Sigmoid:
    def __init__(self):
        self.params, sekf,grads = [], []
        self.out = None
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out=out
        return out
    def backward(self, dout):
        dx = dout*(1.0-self.out)*self.out
class Affine:
    def __init__(self, w, b):
        self.params=[w, b]
        self.grads=[np.zeros_like(w),np.zeros_like(b)]
        self.x=None
    def forward(self, x):
        w, b = self.params
        out=np.dot(x, w) + b
        self.x=x
        return out
    def backward(self, dout):
        w, b=self.params
        dx=np.dot(dout,w.T)
        dw=np.dot(self.x.T, dout)
        db=np.sum(dout,axis=0)
        self.grads[0][...]=dw
        self.grads[1][...]=db

In [1]:
class TwoLayerNet:
    def __init__(self, inputSize, hiddenSize, outSize):
        I, H, O=inputSize, hiddenSize, outSize
        w1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        w2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        self.layers=[
            Affine(w1, b1),
            Sigmoid(),
            Affine(w2, b2)
        ]
        self.params=[]
        for layer in self.layers:
            self.params += layer.params
    def predict(self, x):
        for layer in self.layers:
            x=layer.forward(x)
        return x

def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    # 教師データがone-hot-vectorの場合、正解ラベルのインデックスに変換
    if t.size == y.size:
        t = t.argmax(axis=1)
             
    batch_size = y.shape[0]

    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

class Softmax:
    def __init__(self):
        self.params, self.grads = [], []
        self.out = None

    def forward(self, x):
        self.out = softmax(x)
        return self.out

    def backward(self, dout):
        dx = self.out * dout
        sumdx = np.sum(dx, axis=1, keepdims=True)
        dx -= self.out * sumdx
        return dx


class SoftmaxWithLoss:
    def __init__(self):
        self.params, self.grads = [], []
        self.y = None  # softmaxの出力
        self.t = None  # 教師ラベル

    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)

        # 教師ラベルがone-hotベクトルの場合、正解のインデックスに変換
        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)

        loss = cross_entropy_error(self.y, self.t)
        return loss

    def backward(self, dout=1):
        batch_size = self.t.shape[0]

        dx = self.y.copy()
        dx[np.arange(batch_size), self.t] -= 1
        dx *= dout
        dx = dx / batch_size

        return dx

class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
    def forward(self, x):
        W, = self.params
        out = np.dot(x,W)
        self.x = x
        return out
    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx


In [9]:
class SGD:
    def __init__(self, lr=0.001):
        self.lr=lr
    def update(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr*grads[i]

[[-0.4384907  -0.56200297  2.58112462]
 [-0.62524104 -1.10831812  2.1534526 ]
 [-0.86117219 -1.06153892  1.92946717]
 [-0.50038535  0.56464442  2.79866687]
 [-0.59948536 -0.22650216  2.53088916]
 [-0.59450209  0.09353349  2.59236385]
 [-0.64335117 -0.13655122  2.51704611]
 [-0.90921192 -0.41578402  2.2821416 ]
 [-0.78638036 -0.36504226  2.37267306]
 [-0.60079562 -1.18473907  2.09632761]]
